In [1]:
plus = 0
for i in range(1, 4):
    for j in range(1,3):
        plus += i + j
print(plus)

21


In [2]:
[f'({i}+{j})' for i in range(1, 3) for j in range(1, 4)]


['(1+1)', '(1+2)', '(1+3)', '(2+1)', '(2+2)', '(2+3)']

In [3]:
[i+j for i in range(1,3) for j in range(1,4)]

[2, 3, 4, 3, 4, 5]

In [19]:
import numpy as np

In [4]:
sum([i+j for i in range(1,3) for j in range(1,4)])

21

In [6]:
import numpy as np


In [7]:
i = np.arange(1,3).reshape((2,-1))
j = np.arange(1,4).reshape(-1,3)
i+j

array([[2, 3, 4],
       [3, 4, 5]])

In [8]:
result=np.array([i+2*j for i in range(1,4) for j in range(1,3)])

In [10]:
result=np.cumprod([i+2*j for i in range(1,4) for j in range(1,3)])

In [11]:
result[-1]

12600

In [12]:
import numpy as np

def euclidean_distance(point1, point2):
    return np.linalg.norm(np.array(point1)-np.array(point2))

point1 = [1, 2]
point2 = [4, 6]
distance = euclidean_distance(point1, point2)
print(f"Eucledean Distance: {distance}")

Eucledean Distance: 5.0


In [14]:
def manhattan_distance(point1, point2, p):
    return np.sum(np.abs(np.array(point1) - np.array(point2)))

point1 = [1,2]
point2 = [4,6]
distance = manhattan_distance(point1, point2, p=3)
print(f"Manhattan_distance(p=3): {distance}")

Manhattan_distance(p=3): 7


In [20]:
def minkowski_distance(point1, point2, p):
    return np.sum(np.abs(np.array(point1)- np.array(point2))**p)**(1/p)
point1 = [1,2]
point2 = [4,6]
distance = minkowski_distance(point1, point2, p=3)
print(f"minkowski_distance(p=3): {distance}")

minkowski_distance(p=3): 4.497941445275415


In [21]:
def f(x):
    return x**3 + 1
def g(x):
    return np.sqrt(x+2)

print("(g o f)(2) = ", g(f(2)))
print("(f o g)(2) = ", f(g(2)))
print("(g o g)(2) = ", g(g(2)))


(g o f)(2) =  3.3166247903554
(f o g)(2) =  9.0
(g o g)(2) =  2.0


In [22]:
height = np.array([166,168,170,172,174])
weight = np.array([40, 70, 60, 55, 78])

cov_matrix = np.cov(weight, height)
corr_matrix = np.corrcoef(weight, height)

cov_w_h = cov_matrix[0,1]
corr_w_h = corr_matrix[0,1]

print("공분산:", cov_w_h)
print("상관계수:", corr_w_h)

공분산: 30.5
상관계수: 0.6627303526338384


In [23]:
import numpy as np
adc = np.array([13,8,10,15,12,15,14,15,17,19,20,21,22,21,25])
sls = np.array([94,70,90,100,95,100,85,95,105,105,110,105,104,105,121])
cov_matrix = np.cov(adc, sls)
corr_matrix = np.corrcoef(adc,sls)
cov_a_d = cov_matrix[0,1]
corr_a_d = corr_matrix[0,1]

print("공분산:", cov_a_d)
print("상관계수:", corr_a_d)



공분산: 50.24761904761905
상관계수: 0.8879209022406115


In [27]:
import pandas as pd


In [29]:
df_sales = pd.read_csv("C:\\Users\\user\\Downloads\\매출과광고상관.csv", encoding='cp949')

In [31]:
df_sales.values

array([[ 13,  94],
       [  8,  70],
       [ 10,  90],
       [ 15, 100],
       [ 12,  95],
       [ 15, 100],
       [ 14,  85],
       [ 15,  95],
       [ 17, 105],
       [ 19, 105],
       [ 20, 110],
       [ 21, 105],
       [ 22, 104],
       [ 21, 105],
       [ 25, 121]], dtype=int64)

In [30]:
type(df_sales)

pandas.core.frame.DataFrame

In [32]:
df_sales.describe()

광고비         매출액
count  15.000000   15.000000
mean   16.466667   98.933333
std     4.793845   11.804761
min     8.000000   70.000000
25%    13.500000   94.500000
50%    15.000000  100.000000
75%    20.500000  105.000000
max    25.000000  121.000000

In [33]:
df_sales.광고비

0     13
1      8
2     10
3     15
4     12
5     15
6     14
7     15
8     17
9     19
10    20
11    21
12    22
13    21
14    25
Name: 광고비, dtype: int64

In [36]:
type(df_sales['광고비'])


pandas.core.series.Series

In [37]:
df_sales.info

<bound method DataFrame.info of     광고비  매출액
0    13   94
1     8   70
2    10   90
3    15  100
4    12   95
5    15  100
6    14   85
7    15   95
8    17  105
9    19  105
10   20  110
11   21  105
12   22  104
13   21  105
14   25  121>

In [40]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
[i for i in np.arange(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
np.ones(3)

array([1., 1., 1.])

In [46]:
lil=[[1,2,3],[4,5,6],[7,8,9]]
lil[0][0]

1

In [47]:
np.array(lil)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arrd2=np.array(lil)

In [49]:
arrd2.ndim

2