In [1]:
import numpy as np

In [2]:
np.random.seed(0)
print(np.random.random(3))
np.random.seed(2)
print(np.random.random(3))
np.random.seed(0)
print(np.random.random(3))


[0.5488135  0.71518937 0.60276338]
[0.4359949  0.02592623 0.54966248]
[0.5488135  0.71518937 0.60276338]


In [3]:
np.random.randint(0,3)

1

In [4]:
x=np.array([0,1,2,3,4,5])
np.sqrt(x)
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [5]:
2.718281**2

7.389051594961001

In [ ]:
a=np.array([2,-3,4,5,7,0,1,-1])
a.argmax()
#최댓값의 위치를 알려줌.


4

In [8]:
A=np.array([0,1,2,3]).reshape(2,2)


In [9]:
A

array([[0, 1],
       [2, 3]])

In [10]:
B=np.array([3,2,0,1,]).reshape(2,2)


In [11]:
B

array([[3, 2],
       [0, 1]])

In [13]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [14]:
A@B

array([[0, 1],
       [6, 7]])

In [15]:
A=np.array([3,4,1,0,5,2]).reshape(2,3)
A.transpose()

array([[3, 0],
       [4, 5],
       [1, 2]])

In [16]:
A.T

array([[3, 0],
       [4, 5],
       [1, 2]])

In [17]:
A

array([[3, 4, 1],
       [0, 5, 2]])

In [18]:
np.linalg.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

In [26]:
c=np.array([[[0,1,2,3],
            [4,5,6,7],
            [8,9,10,11]
            ],
           [[5,5,6,6],
            [4,5,6,7],
            [8,9,10,11]
            ]]
           )


In [27]:
c[1,0:2,1:3]

array([[5, 6],
       [5, 6]])

In [30]:
a1=np.array([0,10,20,30,40,50])
a1[5]=70
a1[5]

70

In [34]:
a2=np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [37]:
a2[0,2]

30

In [45]:
a2[2]=np.array([45,55,65])
a2

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

In [47]:
a2[[0,2],[0,1]]

array([10, 55])