In [5]:
import pandas as pd

In [10]:
df_iris=pd.read_csv("C:/ex/data/iris.csv")

In [11]:
df_iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [13]:
A=np.array([1,-4,-4,1]).reshape(2,2)
B=np.array([1,-8,-8,2]).reshape(2,2)


In [15]:
A+B

array([[  2, -12],
       [-12,   3]])

In [16]:
A=np.array([2,3,1,4,5,1]).reshape(2,3)
B=np.array([-1,2,4,-2,3,6]).reshape(3,2)

In [22]:
A@B

array([[13,  4],
       [19,  4]])

In [21]:
np.dot(A,B)

array([[13,  4],
       [19,  4]])

In [20]:
import numpy as np